using System.Text.Json.Serialization;

namespace School_Parent_App.Models
{
    public class Parent
    {
        public int ParentId { get; set; }

        // Autogenerated RegistrationId
        public long RegistrationId { get; set; }
        public string ParentName { get; set; }
        public string StudentName { get; set; }
        public string StudentRegisterNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PrimaryContactPerson { get; set; }
        public string PrimaryContactPersonMobile { get; set; }
        public string SecondaryContactPerson { get; set; }
        public string SecondaryContactPersonMobile { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Password { get; set; }
        public string SetPassword { get; set; }
        public string Status { get; set; }


    }
}